### ISSUE TITLE
Bug - Blocked Content is loaded incorrectly in Ticketzoom

### ISSUE THREAD

**Issue by illovv** [znuny/Znuny#454] opened 2023-06-27 09:02 UTC
### Environment

- OS:          any
- Browser:      any
- Znuny version: 7.0.5

### Expected behaviour

After clicking on "load blocked content" in the ticketzoom view, Znuny should load the blocked content of the mail, which was sent.

### Actual behaviour

The Dashboard is displayed instead of the content of the mail, when clicking "load blocked content"

### How to reproduce

1. Open a ticket, where Content was blocked
2. Click on load blocked content

### Screenshots

![Bug1](https://github.com/znuny/Znuny/assets/62100810/79b45a90-3208-41de-9eef-6476aea0929d)

![Bug2](https://github.com/znuny/Znuny/assets/62100810/72a771aa-cb3f-4bbf-ac25-0187c46ace4f)

**Comment by rkaldung** [comment] 2023-06-29 17:38
@dignin Please check if this behavior exists in the latest patch level (7.0.7)

**Comment by greinick** [comment] 2023-07-03 06:55
HI, I see that bug still in znuny 7.0.7 :(

**Comment by dignin** [comment] 2023-07-03 08:18
Hi, as you see, we created an internal issue ;) Thanks for the follow-up. 658

**Comment by illovv** [comment] 2023-07-03 13:32
> @dignin Please check if this behavior exists in the latest patch level (7.0.7)

checked and I can confirm, that the problem still exist.

**Comment by dignin** [comment] 2023-07-04 06:36
Yes, thanks for that additional feedback. FYI: We only create internal MRs ,if the problem exists in the latest version. We'll get back to you here when it's fixed.

**Comment by dennykorsukewitz** [comment] 2023-08-21 07:40
internal issue 658

**Comment by greinick** [comment] 2023-09-06 07:00
Hi, after updating from Znuny 7.0.9 to the recent 7.0.10, we still have that issue :( ... May be we missed to check/update/clean up some temp or cache?

**Comment by dennykorsukewitz** [comment] 2023-09-06 07:02
@dignin can you verify this again, please.

**Comment by dignin** [comment] 2024-01-18 14:26
Hi @greinick , I cannot reproduce the error in the most current version. If you can, please provide me with the message causing the error. I will close the issue for now because I can't reproduce it. You are welcome to, with further details, if you are still having issues.

**Closed as completed by dignin** 2024-01-18 14:26 UTC
Labels: 1 - 🐞  bug 🐞, 3 - verified, 3 - internal Issue/MR
