### ISSUE TITLE
Bug - "Link" time zones not working

### ISSUE THREAD

**Issue by chrullrich** [znuny/Znuny#281] opened 2022-08-17 08:16 UTC
### Environment

- OS:           FreeBSD
- Browser:      irrelevant
- Znuny version: 6.4.2

### Expected behaviour

Znuny should work correctly while the time zone configured in the user preferences is valid according to the time zone database (i.e. creatable via DateTime::TimeZone->new()).

### Actual behaviour

Znuny responds to any request with a blank page if the time zone is a "Link" zone, i.e. an alias for another one.

### How to reproduce

1. Install a version of DateTime::TimeZone before 2.53.
2. Set the user preference time zone to "Europe/Luxembourg".
3. Update DateTime::TimeZone to 2.53.

### Additional information

DateTime::TimeZone 2.53 relegated a number of time zone names, such as Europe/Amsterdam, Africa/Abidjan, Asia/Brunei, and the aforementioned Luxembourg, to aliases of other zones. Because Kernel::System::DateTime::IsTimeZoneValid() considers only the "real" time zone names (DateTime::TimeZone::Catalog::ALL, but not LINKS) as valid, these zone names now do not work anymore.

There are many more such "Link" zone names, and more "real" zone names may become such aliases in the future.

Possible fix (suggested by someone with very little knowledge of Perl):

1. Use DateTime::TimeZone->is_valid_name() to validate individual zone names, instead of relying on only a part of the full list of names obtained from DateTime::TimeZone::Catalog::all_names(). This will allow existing installations to continue working if a configured time zone name becomes an alias later on.
2. Combine data from DateTime::TimeZone::Catalog::ALL and DateTime::TimeZone::Catalog::LINKS into the selection list;  ...Catalog::all_names() also returns only the "real" zone names, not the aliases.

**Comment by rkaldung** [comment] 2022-08-17 14:57
Hi @chrullrich,

Thank you for reporting, I can confirm that there is an issue with v2.5.3 of DateTime::TimeZone. I cannot reproduce the blank page, this should be not the case if you restart the web server when using mod_perl.
But I can confirm that a user with the TZ Europe/Luxembourg does not see his selected TZ and the system switches back for him to UTC.

**Comment by chrullrich** [comment] 2022-08-17 15:03
> I cannot reproduce the blank page, this should be not the case if you restart the web server when using mod_perl.

I don't; I use the FastCGI scripts.

> But I can confirm that a user with the TZ Europe/Luxembourg does not see his selected TZ and the system switches back for him to UTC.

The difference in Perl engine probably explains this, too. When I hacked around the problem by changing `IsTimeZoneValid()` to use `DateTime::TimeZone->is_valid_name()` the UI worked and told me I had nine invalid settings deployed (eight calendars and OTRSTimeZone, I think). Plus the user's time zone itself.

**Comment by rkaldung** [comment] 2022-08-19 15:15
@chrullrich This issue will be fixed in Znuny LTS 6.0.46 and Znuny 6.4.3

**Comment by rkaldung** [comment] 2022-09-08 08:15
Fixed with c4094db16ff569e9c25da07d6bbb9baba0874444 and  6d85958a88dcc76ff5b6fae70e5f90d4a162833d

**Closed as completed by rkaldung** 2022-09-08 08:15 UTC
Labels: 1 - 🐞  bug 🐞, 3 - verified, 3 - internal Issue/MR
