### ISSUE TITLE
Message template disables ACL on process activity windows

### ISSUE THREAD

**Issue by lis975** [znuny/Znuny#332] opened 2023-01-05 14:30 UTC
### Environment

- OS:  Linux
- Browser:   Safari, Chrome 
- Znuny version: 6.4.3

### Expected behaviour

Setting Message template on activity window in Process ticket do not affect ACL on other components

### Actual behaviour

I have an Queue component on process ticket on top of some activity window, which is restricted only to few queues for customer/agent selection. On the same window I also have a Message component, which has one template attached.

In effect if there is any restricted by ACL dropdown list below Message, that isn't set before choosing a template, after the template is set the list is not restricted by ACL anymore.

### How to reproduce

If user chooses: 

1. first queue, next message template - everything works fine.
2. If user chooses: first message template, the queue component isn't anymore restricted by ACL, the default "Raw" queue is automatically set. 
The problem is that not only message component is cleared after setting message template, but the entire activity window.

**Comment by KaiHerlemann** [comment] 2023-01-06 15:49
I guess that you are filtering by ActivityEntityID and ProcessEntityID in your ACL. Is that correct?
In this case the problem is already solved. The change will be included in the next release.
See also issue #316, this issue concerns the same problem.

**Comment by lis975** [comment] 2023-01-06 22:40
Yes, you’ve right. Thank you very much for your explanation nad assistance!

Daniel Lisiecki

**Closed as completed** 2023-01-06 22:40 UTC
Labels: 3 - duplicate, 3 - verified, 3 - internal Issue/MR
