### ISSUE TITLE
Bug - "Create Your First Ticket" button in customer interface with wrong format when language is PT-BR

### ISSUE THREAD

**Issue by maureliosilverio** [znuny/Znuny#356] opened 2023-03-31 12:12 UTC
### Environment

- OS: Ubuntu 20.04
- Browser:   Firefox 111.0.1 and  Chrome 111.0.5563.147
- Znuny version: 7.0.2

### Expected behaviour

When the customer accesses the interface for the first time, a button to create his first ticket appears. In English the format is correct:

![image](https://user-images.githubusercontent.com/1065844/229113850-1802f029-7b37-4379-a36a-d2bc894dc5ab.png)

### Actual behaviour

When the customer's language is Brazillian Portuguese, the button gets a weird format:

![image](https://user-images.githubusercontent.com/1065844/229114153-63d905f3-372e-401b-b7cf-3a2fd072cdee.png)

### How to reproduce

Steps to reproduce the behaviour:

1. Go to 'customer interface.'
2. Change language to Portuguese BR
3. Click on 'My Tickets'
4. 4. See error

### Additional information

Also tested in Spanish, Italian and European Portuguese, but no issues were found.

**Comment by hanneshal** [comment] 2023-03-31 12:23
@maureliosilverio We don't tell anyone where our designer are located and just fix this issue ;) 

Thanks for your feedback.

**Comment by maureliosilverio** [comment] 2023-03-31 12:32
@hanneshal that was fast :)
Thanks!!

**Comment by dignin** [comment] 2023-04-11 07:38
The issue is fixed in the next release. Thanks for your report.

**Closed as completed by dignin** 2023-04-11 07:38 UTC

**Comment by maureliosilverio** [comment] 2023-04-21 17:46
Hi, sorry to reopen this thread, but version 7.0.3 still has the same problem:

![image](https://user-images.githubusercontent.com/1065844/233701530-5160bacf-14bc-42ba-89e0-7ab884249190.png)

Thank you.
